name: Build README

on:
  push:
  workflow_dispatch:
  schedule:
    # https://crontab.guru/#0_2_*_*_*
    - cron: '0 2 * * *'

jobs:
  build:
    runs-on: macOS-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: |
          npm ci
      - name: Update README
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        run: |-
          touch .env
          echo ACCESS_TOKEN =${{ secrets.ACCESS_TOKEN }} >> .env
          npm start
          cat README.md
      - name: Commit and push if changed
        run: |-
          git add .
          git diff
          git config --global user.email "github-action-bot@example.com"
          git config --global user.name "GitHub Action Bot"
          git commit -m "Updated README" -a || echo "No changes to commit"
          git push
      - name: Post Process
        env:
          NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
        run: |-
          npm run postProcess
